#######################################################################################################################################
#######################################################################################################################################
#### Tokens 
### Literals
## Integer literals
DECIMAL_INTEGER_LITERAL ::= [0-9]+([eE][0-9]+)?
BASED_INTEGER_LITERAL ::= [0-9]{1,2}_[0-9]+
INTEGER_LITERAL ::= DECIMAL_INTEGER_LITERAL | BASED_INTEGER_LITERAL
## Real literals
REAL_LITERAL ::= [0-9]*\.[0-9]+([eE][+-]?[0-9]+)?
## Complex literals
COMPLEX_LITERAL ::= (REAL_LITERAL | INTEGER_LITERAL) [iIjJ]
## Character literals
CHAR ::= [\x20 - \x90] | [\x93 - \xFF]
ESCAPE_SEQUENCE ::= \\[\x20 - \xFF]
CHAR_LITERAL ::= '(CHAR | ESCAPE_SEQUENCE)' 
## String literals 
SCHAR ::= [\x20 - \x93] | [\x95 - \FF]
ESCAPE_SEQUENCE ::= \\[\x20 - \xFF]
STRING_LITERAL ::= "(CHAR_LITERAL | ESCAPE_SEQUENCE)*"

### Identifiers
[_a-zA-ZA-Z][-_a-zA-Z]*

### Punctuators
"[" "]" "(" ")" "{" "}" ";" ":" "=>"

### Operators 
## Arithmetic Operators
"+" "-" "*" "/" "//" "^" "%" 
"+=" "-=" "*=" "/=" "//=" "^=" "%="

## Element-Wise Arithmetic Operators
"+<" "-<" "*<" "/<" "//<" "^<" "%<"
"+<=" "-<=" "*<=" "/<=" "//<=" "^<=" "%<="

## Logical Operators 
"&&" "||" "!" "<" "<=" "<=>" ">=" ">" "==" "!="

## Bitwise Operators 
"&" "|" "^^" "~" "<<" ">>"
"&=" "|=" "^^=" "~=" "<<=" ">>="

## Element-Wise Bitwise Operators 
"&<" "|<" "^^<" "~<" "<<<" ">><"
"&<=" "|<=" "^^<=" "~<=" "<<<=" ">><="

## Miscellaneous Operators 
"=" "<-" "++" "--" "..." "&" "::" "." "?:" (ternary operator)

### Keywords
## Built-in-Types 
int8_t int16_t int32_t int64_t int (alias for int32_t) real32_t real64_t real (alias for real64_t) bool char mod (modular types) void

## Literals 
true false this nptr

## Declarations 
# General 
let const compeval 
# Function 
pure static nothrow in inout out move operator delete 
# Class 
class public protected private enum constructor destructor default
# Type Alias 
define 

## Control Flow 
if else if else for do which try catch throw break return continue match when 

## Generic 
typeset template where

## Modules 
module namespace import from as with

## Expressions 
as is in sizeof typeof static_assert new dynamic