#line 2 "/home/aschiffe/Dev/Nikola-c/Nikolac/src/Parser/NikolaLexer.cpp"

#line 4 "/home/aschiffe/Dev/Nikola-c/Nikolac/src/Parser/NikolaLexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */
/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* begin standard C++ headers. */
/* %if-c++-only */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */
/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */
/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
/* %endif */

/* %if-c++-only */
	std::streambuf* yy_input_file;
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %if-not-reentrant */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */
/* %if-not-reentrant */
/* %not-for-header */
/* %ok-for-header */

/* %endif */
/* %endif */

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int Nikola::SyntaxAnalysis::NikolaLexer::yylex()

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */
/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 159
#define YY_END_OF_BUFFER 160
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[385] =
    {   0,
        0,    0,  160,  158,    2,    1,   48,  158,  158,   24,
       56,  158,   11,   12,   20,   18,   19,   86,   21,    4,
       16,   15,   49,   80,   52,   87,  157,    9,   10,   23,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,   13,   57,   14,
       59,    2,    1,   55,    0,    8,    0,    0,   38,   31,
       46,   68,   62,    0,    0,   34,   27,   82,   32,   25,
       83,   33,   26,    0,    5,   22,   35,   28,    0,    4,
        6,    0,   85,   81,   60,   50,   54,   17,   53,   61,
      157,   37,   30,   58,  148,  157,  157,  157,  157,  157,

      157,  157,  130,  157,  157,  157,  157,  157,  157,  126,
      157,  110,  150,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,   69,   63,   47,   71,   65,    0,
        8,    0,    3,   45,   74,    7,    7,   41,   39,   40,
       84,    0,   36,   29,   42,    4,    4,   72,   66,   51,
       73,   67,   44,   70,   64,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      129,  157,  157,  157,   92,  104,  157,   98,  157,  157,
      155,  157,  157,  157,  112,  157,  157,  157,  157,  157,

      157,  157,  157,  157,  157,  157,  157,  132,  157,  157,
      157,  157,  157,   75,   77,    0,    5,   43,    0,   78,
       79,   76,  157,   96,  157,  157,   97,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  127,  121,  157,  147,
      157,  157,  157,  157,  157,  157,  157,  157,  113,  157,
      157,  103,  157,  157,  157,  157,  107,   95,  157,  157,
      157,  157,  102,  157,  100,  143,   99,  139,  157,  157,
      149,  157,  135,  133,  117,  157,  105,  157,  157,  157,
      157,  157,  157,    0,  101,  157,  111,  157,  157,  157,
      157,  138,  157,  157,  157,  157,  157,  157,  157,  157,

      157,  157,  157,  157,  157,  134,  157,  157,  142,  131,
      154,  157,  157,  157,  157,  125,  115,  157,  157,    0,
      146,  157,  157,  157,   88,  144,  157,  157,  157,  157,
      157,  118,  157,  157,  136,  151,  108,  157,  152,  157,
      157,  157,  157,  116,  157,  156,  128,   89,   90,   91,
      157,  109,  157,  120,  157,  157,  157,  157,  157,  140,
      106,  157,  137,  157,  157,  114,  157,   93,   94,  157,
      141,  157,  157,  145,  119,  157,  157,  123,  157,  122,
      157,  157,  153,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,    8,   16,   17,   18,   19,   20,   21,
       22,   23,   19,   24,   19,   25,   19,   26,   27,   28,
       29,   30,   31,    8,   32,   32,   32,   32,   33,   32,
       32,   32,   34,   34,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       35,   36,   37,   38,   39,    8,   40,   41,   42,   43,

       44,   45,   32,   46,   47,   34,   48,   49,   50,   51,
       52,   53,   32,   54,   55,   56,   57,   58,   59,   32,
       60,   61,   62,   63,   64,   65,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,   66,   66,    8,   67,   67,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8
    } ;

static const YY_CHAR yy_meta[68] =
    {   0,
        1,    1,    2,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    4,    5,    3,    6,    6,
        6,    6,    6,    6,    6,    3,    3,    3,    3,    3,
        3,    7,    8,    6,    3,    3,    3,    3,    9,    7,
        7,    7,    7,    8,    7,    7,    6,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    3,    3,    3,    3,   10,   11
    } ;

static const flex_int16_t yy_base[394] =
    {   0,
        0,    0,  523,  524,   66,   69,  493,   68,    0,   47,
       67,  485,  524,  524,   50,   65,   69,   67,   81,   66,
      494,  524,   86,   52,   77,  524,    0,  524,  524,   83,
      464,   49,   76,   74,   68,   83,   88,  474,   68,   92,
       74,   92,  473,   94,  107,  464,   83,  524,  119,  524,
      126,  154,  160,  524,  134,  136,  153,  512,  485,  524,
      524,  484,  524,  501,  113,  482,  524,  524,  481,  524,
      524,  480,  524,  491,  140,  137,  478,  524,  171,  163,
      524,    0,  524,  524,  140,  476,  524,  524,  524,  147,
        0,  476,  524,  149,  449,  451,  458,  445,  460,  459,

      135,  154,    0,  447,  442,  439,  446,  440,  441,    0,
      439,  148,    0,  435,  434,  140,  439,  429,  431,  430,
      441,  428,  154,  164,  167,  422,  442,  431,  134,  151,
      427,  432,  168,  422,  448,  524,  524,  447,  524,  207,
      208,  210,  524,  524,  524,  524,  464,  524,  524,  524,
      524,  206,  445,  524,  524,  215,  434,  443,  524,  524,
      442,  524,  524,  441,  524,  425,  419,  427,  424,  411,
      409,  410,  186,  177,  418,  405,  420,  415,  408,  402,
        0,  406,  403,  397,  228,    0,  411,  395,  407,  406,
        0,  403,  394,  393,    0,  388,  389,  395,  399,  393,

      384,  396,  383,  385,  382,  384,  391,    0,  390,  390,
      200,  383,  385,  524,  524,  236,  244,  524,  236,  524,
      524,  524,  376,    0,  381,  382,    0,  372,  382,  369,
      377,  366,  371,  365,  366,  369,  414,    0,  373,    0,
      362,  359,  390,  392,  389,  372,  364,  360,    0,  353,
      353,    0,  366,  365,  360,  356,    0,  223,  348,  349,
      353,  350,    0,  339,    0,  219,    0,    0,  353,  352,
        0,  339,    0,    0,    0,  336,  339,  341,  342,  346,
      345,  331,  340,  339,    0,  329,    0,  345,  344,  343,
      325,    0,  336,  326,  326,  321,  320,  333,  332,  352,

      349,  320,  325,  327,  328,    0,  322,  322,    0,    0,
        0,  325,  307,  306,  306,    0,    0,  319,  318,  314,
        0,  302,  301,  300,    0,    0,  315,  295,  301,  308,
      295,    0,  307,  306,    0,    0,  302,  270,    0,  267,
      273,  276,  257,    0,  234,    0,  524,    0,    0,    0,
      247,    0,  234,    0,  243,  230,  229,  244,  238,    0,
        0,  225,    0,  228,  235,    0,  233,    0,    0,  220,
        0,  221,  218,    0,    0,  178,  165,    0,  127,    0,
      106,   96,    0,  524,  289,  299,  308,  315,  321,  328,
      334,  338,  342

    } ;

static const flex_int16_t yy_def[394] =
    {   0,
      384,    1,  384,  384,  384,  384,  384,  385,  386,  384,
      384,  387,  384,  384,  384,  384,  384,  384,  384,  388,
      384,  384,  384,  384,  384,  384,  389,  384,  384,  384,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  384,  384,  384,
      384,  384,  384,  384,  385,  385,  390,  386,  384,  384,
      384,  384,  384,  384,  387,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  391,  384,  384,  384,  384,  392,
      384,  393,  384,  384,  384,  384,  384,  384,  384,  384,
      389,  384,  384,  384,  389,  389,  389,  389,  389,  389,

      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  384,  384,  384,  384,  384,  385,
      385,  390,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  393,  384,  384,  384,
      384,  384,  384,  384,  384,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,

      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  384,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,

      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  384,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  384,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,    0,  384,  384,  384,  384,  384,  384,
      384,  384,  384

    } ;

static const flex_int16_t yy_nxt[592] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,    4,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   22,   23,   24,   25,
       26,   27,   27,   27,   28,    4,   29,   30,   27,   31,
       32,   33,   34,   35,   36,   27,   37,   27,   38,   39,
       40,   41,   42,   43,   44,   45,   27,   46,   47,   27,
       27,   48,   49,   50,   51,    4,    4,   52,   52,   52,
       52,   53,   52,   56,   59,   60,   61,   66,   67,   68,
       87,   88,   79,   74,   71,   75,   75,   75,   75,   75,
       75,   75,   69,   70,   62,   63,   72,   73,   76,   81,

       96,   84,   97,   57,   82,   89,   90,  115,   77,   78,
       92,   93,   81,   85,   86,   98,  105,  102,  106,  116,
       94,   99,  107,  147,  100,  103,  121,  101,  133,  134,
      122,  117,  110,  104,  108,  118,  109,  111,  112,   56,
      126,   56,  113,  119,  120,  123,  135,  136,  124,  127,
      128,  383,  129,  138,  139,   52,   52,   52,  141,  382,
      130,   52,   53,   52,  153,  154,  131,  158,  159,   57,
      381,   57,  152,   81,  161,  162,  164,  165,   64,   79,
      205,  137,  188,  152,  172,  173,   81,  206,  142,   75,
       75,   75,   75,   75,   75,   75,   81,  189,  174,  184,

      196,   82,  175,  185,  198,  197,  200,  207,  176,   81,
      208,  211,   56,   56,  212,  141,  232,  199,  380,   55,
      216,  216,  201,  233,  217,  217,  217,  217,  217,  217,
      217,   79,  379,  156,  156,  156,  156,  156,  156,  156,
      230,  231,   57,   57,  300,  142,  301,  243,   81,  244,
      268,  245,  246,  269,  217,  217,  217,  217,  217,  217,
      217,   81,  217,  217,  217,  217,  217,  217,  217,   81,
      307,  378,  377,  308,  376,  375,   55,   81,  374,  373,
      372,  371,   81,  370,  369,  368,  367,  366,  365,  364,
       81,   55,   55,   55,   55,   55,   55,   55,   55,   58,

      363,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       64,   64,   64,   64,   64,   64,   64,  362,   64,   80,
       80,  361,  360,   80,   91,  359,   91,   91,   91,   91,
      140,  140,  140,  140,  140,  140,  140,  140,  140,   75,
      358,   75,  156,  156,  357,  356,  156,  157,  157,  157,
      355,  354,  353,  352,  351,  350,  349,  348,  347,  346,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  336,
      335,  334,  333,  332,  331,  330,  329,  328,  327,  326,
      325,  324,  323,  322,  321,  320,  319,  318,  317,  316,
      315,  314,  313,  312,  311,  310,  309,  306,  305,  304,

      303,  302,  299,  298,  297,  296,  295,  294,  293,  292,
      291,  290,  289,  288,  287,  286,  285,  284,  283,  282,
      281,  280,  279,  278,  277,  276,  275,  274,  273,  272,
      271,  270,  267,  266,  265,  264,  263,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,
      249,  248,  247,  242,  241,  240,  239,  238,  237,  236,
      235,  234,  229,  228,  227,  226,  225,  224,  223,  222,
      221,  220,  219,  218,  146,  215,  214,  213,  210,  209,
      204,  203,  202,  195,  194,  193,  192,  191,  190,  187,
      186,  183,  182,  181,  180,  179,  178,  177,  171,  170,

      169,  168,  167,  166,  163,  160,  155,  151,  150,  149,
      148,  146,  145,  144,  143,  132,  125,  114,   95,   83,
       65,   54,  384,    3,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384

    } ;

static const flex_int16_t yy_chk[592] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        6,    6,    6,    8,   10,   10,   11,   15,   15,   16,
       24,   24,   20,   18,   17,   18,   18,   18,   18,   18,
       18,   18,   16,   16,   11,   11,   17,   17,   19,   20,

       32,   23,   32,    8,   20,   25,   25,   39,   19,   19,
       30,   30,   20,   23,   23,   33,   35,   34,   35,   39,
       30,   33,   36,   65,   33,   34,   41,   33,   47,   47,
       41,   40,   37,   34,   36,   40,   36,   37,   37,   55,
       44,   56,   37,   40,   40,   42,   49,   49,   42,   44,
       45,  382,   45,   51,   51,   52,   52,   52,   57,  381,
       45,   53,   53,   53,   76,   76,   45,   85,   85,   55,
      379,   56,   75,   75,   90,   90,   94,   94,   65,   80,
      129,   49,  116,   75,  101,  101,   75,  129,   57,   79,
       79,   79,   79,   79,   79,   79,   80,  116,  102,  112,

      123,   80,  102,  112,  124,  123,  125,  130,  102,   80,
      130,  133,  140,  141,  133,  142,  174,  124,  377,   57,
      152,  152,  125,  174,  152,  152,  152,  152,  152,  152,
      152,  156,  376,  156,  156,  156,  156,  156,  156,  156,
      173,  173,  140,  141,  258,  142,  258,  185,  156,  185,
      211,  185,  185,  211,  216,  216,  216,  216,  216,  216,
      216,  156,  217,  217,  217,  217,  217,  217,  217,  219,
      266,  373,  372,  266,  370,  367,  142,  217,  365,  364,
      362,  359,  219,  358,  357,  356,  355,  353,  351,  345,
      217,  385,  385,  385,  385,  385,  385,  385,  385,  386,

      343,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      387,  387,  387,  387,  387,  387,  387,  342,  387,  388,
      388,  341,  340,  388,  389,  338,  389,  389,  389,  389,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  391,
      337,  391,  392,  392,  334,  333,  392,  393,  393,  393,
      331,  330,  329,  328,  327,  324,  323,  322,  320,  319,
      318,  315,  314,  313,  312,  308,  307,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  295,  294,  293,
      291,  290,  289,  288,  286,  284,  283,  282,  281,  280,
      279,  278,  277,  276,  272,  270,  269,  264,  262,  261,

      260,  259,  256,  255,  254,  253,  251,  250,  248,  247,
      246,  245,  244,  243,  242,  241,  239,  237,  236,  235,
      234,  233,  232,  231,  230,  229,  228,  226,  225,  223,
      213,  212,  210,  209,  207,  206,  205,  204,  203,  202,
      201,  200,  199,  198,  197,  196,  194,  193,  192,  190,
      189,  188,  187,  184,  183,  182,  180,  179,  178,  177,
      176,  175,  172,  171,  170,  169,  168,  167,  166,  164,
      161,  158,  157,  153,  147,  138,  135,  134,  132,  131,
      128,  127,  126,  122,  121,  120,  119,  118,  117,  115,
      114,  111,  109,  108,  107,  106,  105,  104,  100,   99,

       98,   97,   96,   95,   92,   86,   77,   74,   72,   69,
       66,   64,   62,   59,   58,   46,   43,   38,   31,   21,
       12,    7,    3,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384

    } ;

static const flex_int16_t yy_rule_linenum[159] =
    {   0,
       45,   46,   47,   49,   50,   51,   52,   53,   55,   56,
       57,   58,   59,   60,   61,   62,   63,   65,   66,   67,
       68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
       78,   80,   81,   82,   83,   84,   85,   86,   87,   88,
       89,   90,   91,   92,   93,   95,   96,   97,   98,   99,
      100,  101,  102,  103,  104,  106,  107,  108,  109,  110,
      111,  112,  113,  114,  115,  116,  117,  119,  120,  121,
      122,  123,  124,  125,  126,  127,  128,  129,  130,  132,
      133,  134,  135,  136,  137,  138,  139,  141,  142,  143,
      144,  145,  146,  147,  148,  149,  150,  151,  152,  154,

      155,  156,  157,  159,  160,  161,  163,  164,  165,  166,
      167,  168,  169,  170,  171,  172,  174,  175,  176,  177,
      178,  179,  180,  181,  183,  185,  186,  187,  188,  189,
      190,  191,  192,  193,  194,  195,  196,  197,  198,  200,
      201,  202,  203,  205,  206,  207,  208,  209,  210,  212,
      213,  214,  215,  216,  217,  218,  220,  224
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
#line 4 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
    #include <istream>

    #include "NikolaLexer.hpp"

    #ifdef YY_DECL
    #undef YY_DECL
    #endif

    using Parser = Nikola::SyntaxAnalysis::NikolaParser;
    using Lexer = Nikola::SyntaxAnalysis::NikolaLexer;

    #define YY_DECL Parser::symbol_type Lexer::lex()
    
    #define YY_USER_ACTION loc_.columns(yyleng);

    #ifdef YY_NULL
    #undef YY_NULL
    #endif
    #define YY_NULL Parser::make_YYEOF(loc_)
#line 781 "/home/aschiffe/Dev/Nikola-c/Nikolac/src/Parser/NikolaLexer.cpp"
#line 782 "/home/aschiffe/Dev/Nikola-c/Nikolac/src/Parser/NikolaLexer.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
#include <unistd.h>
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */
/* %if-bison-bridge */
/* %endif */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */
/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define ECHO LexerOutput( yytext, yyleng )
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
\
/* %if-c++-only C++ definition \ */\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
/* %endif */
/* %if-c++-only */
#define YY_FATAL_ERROR(msg) LexerError( msg )
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */
/* %ok-for-header */

/* %not-for-header */
/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define YY_DECL int yyFlexLexer::yylex()
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */
/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyin.rdbuf(std::cin.rdbuf());
/* %endif */

		if ( ! yyout )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyout.rdbuf(std::cout.rdbuf());
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
/* %% [7.0] user's declarations go here */
#line 40 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"


#line 43 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
    loc_.step();

#line 980 "/home/aschiffe/Dev/Nikola-c/Nikolac/src/Parser/NikolaLexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 385 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 524 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				std::cerr << "--scanner backing up\n";
			else if ( yy_act < 159 )
				std::cerr << "--accepting rule at line " << yy_rule_linenum[yy_act] <<
				         "(\"" << yytext << "\")\n";
			else if ( yy_act == 159 )
				std::cerr << "--accepting default rule (\"" << yytext << "\")\n";
			else if ( yy_act == 160 )
				std::cerr << "--(end of buffer or a NUL)\n";
			else
				std::cerr << "--EOF (start condition " << YY_START << ")\n";
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 45 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
loc_.lines(yyleng); loc_.step();
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 46 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
loc_.step();
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 47 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
loc_.step();
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 49 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_INTEGER_LITERAL(yytext, loc_);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 50 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_REAL_LITERAL(yytext, loc_);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 51 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_COMPLEX_LITERAL(yytext, loc_);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 52 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_CHAR_LITERAL(yytext, loc_);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 53 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_STRING_LITERAL(yytext, loc_);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 55 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_LEFT_BRACKET(loc_);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 56 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_RIGHT_BRACKET(loc_);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 57 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_LEFT_PARENTHESIS(loc_);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 58 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_RIGHT_PARENTHESIS(loc_);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 59 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_LEFT_BRACE(loc_);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 60 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_RIGHT_BRACE(loc_);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 61 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_SEMI_COLON(loc_);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 62 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_COLON(loc_);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 63 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_RIGHT_ARROW(loc_);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 65 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_PLUS(loc_);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 66 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_MINUS(loc_);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 67 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_STAR(loc_);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 68 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_SLASH(loc_);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 69 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DOUBLE_SLASH(loc_);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 70 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_CARET(loc_);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 71 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_PERCENT(loc_);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 72 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_PLUS_ASSIGN(loc_);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 73 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_MINUS_ASSIGN(loc_);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 74 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_STAR_ASSIGN(loc_);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 75 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_SLASH_ASSIGN(loc_);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 76 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DOUBLE_SLASH_ASSIGN(loc_);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 77 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_CARET_ASSIGN(loc_);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 78 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_PERCENT_ASSIGN(loc_);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 80 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_PLUS(loc_);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 81 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_MINUS(loc_);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 82 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_STAR(loc_);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 83 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_SLASH(loc_);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 84 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_DOUBLE_SLASH(loc_);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 85 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_CARET(loc_);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 86 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_PERCENT(loc_);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 87 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_PLUS_ASSIGN(loc_);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 88 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_MINUS_ASSIGN(loc_);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 89 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_STAR_ASSIGN(loc_);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 90 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_SLASH_ASSIGN(loc_);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 91 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_DOUBLE_SLASH_ASSIGN(loc_);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 92 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_CARET_ASSIGN(loc_);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 93 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_PERCENT_ASSIGN(loc_);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 95 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DOUBLE_AMP(loc_);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 96 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DOUBLE_PIPE(loc_);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 97 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_BANG(loc_);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 98 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_LESS(loc_);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 99 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_LESS_EQ(loc_);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 100 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_SPACESHIP(loc_);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 101 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_GREATER(loc_);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 102 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_GREATER_EQ(loc_);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 103 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_EQ(loc_);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 104 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_NEQ(loc_);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 106 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_AMP(loc_);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 107 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_PIPE(loc_);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 108 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DOUBLE_CARET(loc_);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 109 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_TILDE(loc_);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 110 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_LEFT_SHIFT(loc_);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 111 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_RIGHT_SHIFT(loc_);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 112 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_AMP_ASSIGN(loc_);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 113 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_PIPE_ASSIGN(loc_);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 114 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DOUBLE_CARET_ASSIGN(loc_);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 115 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_TILDE_ASSIGN(loc_);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 116 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_LEFT_SHIFT_ASSIGN(loc_);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 117 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_RIGHT_SHIFT_ASSIGN(loc_);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 119 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_AMP(loc_);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 120 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_PIPE(loc_);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 121 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_DOUBLE_CARET(loc_);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 122 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_TILDE(loc_);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 123 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_LEFT_SHIFT(loc_);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 124 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_RIGHT_SHIFT(loc_);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 125 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_AMP_ASSIGN(loc_);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 126 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_PIPE_ASSIGN(loc_);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 127 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_DOUBLE_CARET_ASSIGN(loc_);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 128 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_TILDE_ASSIGN(loc_);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 129 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_LEFT_SHIFT_ASSIGN(loc_);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 130 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_RIGHT_SHIFT_ASSIGN(loc_);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 132 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_ASSIGN(loc_);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 133 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_LEFT_ARROW(loc_);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 134 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_PLUS_PLUS(loc_);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 135 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_MINUS_MINUS(loc_);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 136 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_ELLIPSIS(loc_);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 137 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_COLON_COLON(loc_);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 138 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DOT(loc_);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 139 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_QUESTION(loc_);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 141 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_INT8_T(loc_);}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 142 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_INT16_T(loc_);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 143 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_INT32_T(loc_);}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 144 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_INT64_T(loc_);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 145 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_INT(loc_);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 146 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_REAL32_T(loc_);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 147 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_REAL64_T(loc_);}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 148 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_REAL(loc_);}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 149 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_BOOL(loc_);}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 150 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_CHAR(loc_);}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 151 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_MOD(loc_);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 152 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VOID(loc_);}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 154 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_TRUE(loc_);}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 155 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_FALSE(loc_);}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 156 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_THIS(loc_);}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 157 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_NPTR(loc_);}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 159 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_LET(loc_);}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 160 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_CONST(loc_);}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 161 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_COMPEVAL(loc_);}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 163 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_PURE(loc_);}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 164 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_STATIC(loc_);}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 165 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_NOTHROW(loc_);}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 166 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_IN(loc_);}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 167 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_INOUT(loc_);}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 168 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_OUT(loc_);}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 169 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_MOVE(loc_);}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 170 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_OPERATOR(loc_);}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 171 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DELETE(loc_);}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 172 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DEFAULT(loc_);}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 174 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_CLASS(loc_);}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 175 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_PUBLIC(loc_);}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 176 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_PROTECTED(loc_);}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 177 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_PRIVATE(loc_);}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 178 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_ENUM(loc_);}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 179 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_CONSTRUCTOR(loc_);}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 180 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DESTRUCTOR(loc_);}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 181 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DEFAULT(loc_);}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 183 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DEFINE(loc_);}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 185 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_IF(loc_);}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 186 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_ELSE(loc_);}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 187 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_ELSE_IF(loc_);}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 188 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_FOR(loc_);}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 189 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DO(loc_);}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 190 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_WHILE(loc_);}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 191 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_TRY(loc_);}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 192 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_CATCH(loc_);}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 193 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_THROW(loc_);}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 194 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_BREAK(loc_);}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 195 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_RETURN(loc_);}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 196 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_CONTINUE(loc_);}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 197 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_MATCH(loc_);}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 198 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_WHEN(loc_);}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 200 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_TYPESET(loc_);}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 201 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_TEMPLATE(loc_);}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 202 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_WHERE(loc_);}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 203 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_TYPE(loc_);}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 205 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_MODULE(loc_);}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 206 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_NAMESPACE(loc_);}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 207 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_IMPORT(loc_);}
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 208 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_FROM(loc_);}
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 209 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_AS(loc_);}
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 210 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_WITH(loc_);}
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 212 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_IS(loc_);}
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 213 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_SIZEOF(loc_);}
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 214 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_TYPEOF(loc_);}
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 215 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_STATIC_ASSERT(loc_);}
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 216 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_ASSERT(loc_);}
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 217 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_NEW(loc_);}
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 218 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DYNAMIC(loc_);}
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 220 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_IDENTIFIER(yytext, loc_);}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 222 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_YYEOF(loc_);}
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 224 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{
    throw 1;
}
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 228 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1863 "/home/aschiffe/Dev/Nikola-c/Nikolac/src/Parser/NikolaLexer.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
/* %endif */
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */
/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
int yyFlexLexer::yy_get_next_buffer()
/* %endif */
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */
/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_get_previous_state()
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 385 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
/* %endif */
{
	int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 385 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 384);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyunput( int c, char* yy_bp)
/* %endif */
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */
/* %endif */
#endif

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yyinput()
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyrestart( std::istream& input_file )
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/* %if-c++-only */
/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_load_buffer_state()
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
/* %endif */
/* %if-c++-only */
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
/* %endif */
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/* %if-c++-only */
/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

/* %if-c-only */
/* %endif */
/* %if-c++-only */
	b->yy_input_file = file.rdbuf();
/* %endif */
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */
/* %endif */
/* %if-c++-only */
	b->yy_is_interactive = 0;
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypop_buffer_state (void)
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yyensure_buffer_stack(void)
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_push_state( int _new_state )
/* %endif */
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_pop_state()
/* %endif */
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yy_top_state()
/* %endif */
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* %if-reentrant */
/* %endif */
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 228 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"

namespace Nikola::SyntaxAnalysis
{
    NikolaLexer::NikolaLexer(std::istream& in)
    : yyFlexLexer{&in}, loc_{}
    {

    }
}
