#line 2 "/home/aschiffe/Dev/Nikola-c/Nikolac/src/Parser/NikolaLexer.cpp"

#line 4 "/home/aschiffe/Dev/Nikola-c/Nikolac/src/Parser/NikolaLexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */
/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* begin standard C++ headers. */
/* %if-c++-only */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */
/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */
/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
/* %endif */

/* %if-c++-only */
	std::streambuf* yy_input_file;
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %if-not-reentrant */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */
/* %if-not-reentrant */
/* %not-for-header */
/* %ok-for-header */

/* %endif */
/* %endif */

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int Nikola::SyntaxAnalysis::NikolaLexer::yylex()

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */
/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 147
#define YY_END_OF_BUFFER 148
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[342] =
    {   0,
        0,    0,  148,  147,    2,    1,   47,  147,   23,   53,
      147,   10,   11,   19,   17,   18,   83,   20,    3,   15,
       14,   48,   77,   51,   84,  146,    8,    9,   22,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,   12,   54,   13,   56,
        2,    1,    0,    7,    0,   37,   30,   45,   65,   59,
        0,    0,   33,   26,   79,   31,   24,   80,   32,   25,
        0,    4,   21,   34,   27,    0,    3,    5,    0,   82,
       78,   57,   49,   16,   52,   58,  146,   36,   29,   55,
      137,  146,  146,  146,  146,  146,  146,  119,  146,  146,

      146,  146,  146,  115,  146,  107,  139,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,   66,   60,   46,
       68,   62,    0,    7,    0,   44,   71,    6,    6,   40,
       38,   39,   81,    0,   35,   28,   41,    3,    3,   69,
       63,   50,   70,   64,   43,   67,   61,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  118,
      146,  146,  146,   89,  101,  146,   95,  146,  146,  144,
      146,  146,  146,  109,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  121,  146,  146,  146,  146,  146,   72,

       74,    0,    4,   42,    0,   75,   76,   73,  146,   93,
      146,  146,   94,  146,  146,  146,  146,  146,  146,  146,
      116,  146,  136,  146,  146,    0,    0,    0,    0,  146,
      146,  110,  146,  146,  100,  146,  104,   92,  146,  146,
      146,  146,   99,  146,   97,  132,   96,  128,  146,  146,
      138,  146,  124,  122,  146,  102,  146,  146,  146,  146,
      146,    0,   98,  146,  108,    0,    0,    0,    0,  127,
      146,  146,  146,  146,    0,    0,  146,  146,  146,  146,
      123,  146,  146,  131,  120,  143,  146,  146,  146,  114,
      112,  146,    0,  135,    0,    0,    0,   85,  133,  146,

      146,  146,    0,    0,  125,  140,  105,  146,  141,  146,
      146,  146,  113,  145,  117,   86,   87,   88,  146,  106,
      146,    0,    0,  146,  146,  129,  103,  126,  146,  111,
       90,   91,  146,  130,  134,  146,  146,  146,  146,  142,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    7,    8,    9,   10,   11,
       12,   13,   14,    7,   15,   16,   17,   18,   19,   20,
       21,   22,   18,   23,   18,   24,   18,   25,   26,   27,
       28,   29,   30,    7,   31,   31,   31,   31,   32,   31,
       31,   31,   33,   33,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       34,   35,   36,   37,   38,    7,   39,   40,   41,   42,

       43,   44,   31,   45,   46,   33,   47,   48,   49,   50,
       51,   52,   31,   53,   54,   55,   56,   57,   58,   31,
       59,   60,   61,   62,   63,   64,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,   65,   65,    7,   66,   66,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7
    } ;

static const YY_CHAR yy_meta[67] =
    {   0,
        1,    1,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    3,    4,    2,    5,    5,    5,
        5,    5,    5,    5,    2,    2,    2,    2,    2,    2,
        6,    7,    8,    2,    2,    2,    2,    9,    6,    6,
        6,    6,    7,    6,    6,    8,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        2,    2,    2,    2,   10,   11
    } ;

static const flex_int16_t yy_base[350] =
    {   0,
        0,    0,  472,  473,   65,   68,  473,   67,   47,   67,
      436,  473,  473,   50,   65,   69,   67,   81,   66,  445,
      473,   86,  440,   52,  473,    0,  473,  473,   78,  414,
       65,   72,   76,  419,   71,   76,  423,   82,   89,   51,
      409,  421,   83,   91,  412,   97,  473,  118,  473,  120,
      149,  152,  125,  131,  133,  434,  473,  473,  433,  473,
      450,  139,  431,  473,  473,  430,  473,  473,  429,  473,
      440,  126,  134,  427,  473,  155,  148,  473,    0,  473,
      473,  143,  425,  473,  473,  155,    0,  425,  473,  157,
      398,  400,  407,  394,  409,  138,  119,    0,  397,  392,

      397,  391,  392,    0,  390,  138,    0,  386,  385,  148,
      390,  380,  382,  381,  392,  379,  380,  152,  372,  392,
      381,  149,  141,  377,  382,  155,  372,  398,  473,  473,
      397,  473,  186,  190,  197,  473,  473,  473,  414,  473,
      473,  473,  473,  194,  395,  473,  473,  190,  384,  393,
      473,  473,  392,  473,  473,  391,  473,  375,  369,  377,
      374,  361,  361,  156,  180,  369,  372,  367,  355,    0,
      359,  356,  350,  210,    0,  364,  348,  360,  359,    0,
      356,  347,  346,    0,  355,  349,  340,  352,  339,  341,
      338,  340,  347,    0,  346,  346,  174,  339,  341,  473,

      473,  219,  226,  473,  189,  473,  473,  473,  332,    0,
      337,  338,    0,  339,  326,  334,  323,  328,  322,  327,
      371,  331,    0,  320,  317,  348,  350,  347,  330,  322,
      318,    0,  311,  311,    0,  324,    0,  230,  309,  310,
      314,  311,    0,  300,    0,  201,    0,    0,  314,  313,
        0,  300,    0,    0,  297,    0,  303,  304,  308,  307,
      303,  302,    0,  292,    0,  308,  307,  306,  288,    0,
      299,  289,  289,  284,  318,  315,  286,  291,  293,  294,
        0,  288,  288,    0,    0,    0,  291,  273,  267,    0,
        0,  280,  272,    0,  245,  244,  240,  473,    0,  255,

      232,  220,  232,  231,    0,    0,  230,  212,    0,  211,
      217,  221,    0,    0,  473,  473,  473,  473,  221,    0,
      208,  205,  203,  218,  213,    0,    0,    0,  211,    0,
      473,  473,  176,    0,    0,  166,  122,  104,   45,    0,
      473,  271,  280,  288,  295,  303,  310,  315,  320
    } ;

static const flex_int16_t yy_def[350] =
    {   0,
      341,    1,  341,  341,  341,  341,  341,  342,  341,  341,
      343,  341,  341,  341,  341,  341,  341,  341,  344,  341,
      341,  341,  341,  341,  341,  345,  341,  341,  341,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  341,  341,  341,  341,
      341,  341,  342,  342,  346,  341,  341,  341,  341,  341,
      341,  343,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  347,  341,  341,  341,  341,  348,  341,  349,  341,
      341,  341,  341,  341,  341,  341,  345,  341,  341,  341,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,

      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  341,  341,  341,
      341,  341,  342,  342,  346,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  348,  349,  341,
      341,  341,  341,  341,  341,  341,  341,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  341,

      341,  341,  341,  341,  341,  341,  341,  341,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  341,  341,  341,  341,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  341,  345,  345,  345,  341,  341,  341,  341,  345,
      345,  345,  345,  345,  341,  341,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  341,  345,  341,  341,  341,  341,  345,  345,

      345,  345,  341,  341,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  341,  341,  341,  341,  345,  345,
      345,  341,  341,  345,  345,  345,  345,  345,  345,  345,
      341,  341,  345,  345,  345,  345,  345,  345,  345,  345,
        0,  341,  341,  341,  341,  341,  341,  341,  341
    } ;

static const flex_int16_t yy_nxt[540] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   20,   21,   22,   23,   24,   25,
       26,   26,   26,   27,    4,   28,   29,   26,   30,   31,
       32,   33,   34,   35,   26,   36,   26,   37,   38,   39,
       40,   41,   42,   43,   44,   26,   45,   46,   26,   26,
       47,   48,   49,   50,    4,    4,   51,   51,   51,   51,
       52,   51,   54,   56,   57,   58,   63,   64,   65,   85,
       86,   76,   71,   68,   72,   72,   72,   72,   72,   72,
       72,   66,   67,   59,   60,   69,   70,   73,   78,  340,

       81,   55,  115,   79,   88,   89,  116,   74,   75,  101,
       94,   78,   82,   83,   90,   92,   95,   93,   97,  104,
      109,  102,   96,  103,  105,  106,   98,  111,  119,  107,
       54,  112,  110,  121,   99,  122,   54,  120,  134,  113,
      114,  126,  127,  123,  128,  129,  131,  132,  139,  124,
       51,   51,   51,   51,   52,   51,  339,  144,   78,   55,
      145,  146,  165,   76,  338,   55,  166,  135,  144,  150,
      151,   78,   72,   72,   72,   72,   72,   72,   72,  130,
       78,  153,  154,  156,  157,   79,  163,  164,  173,  177,
      186,   54,  174,   78,  191,   54,  193,  197,   53,  194,

      198,  192,  134,   61,  178,   76,  187,  202,  202,  215,
      216,  203,  203,  203,  203,  203,  203,  203,  217,  337,
       55,   78,   78,  248,   55,  218,  249,  341,  226,  336,
      227,  135,  228,  229,   78,   78,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      275,  282,  276,  335,  283,  334,  333,  332,   78,  331,
      330,  329,   53,  328,  327,  326,  325,  324,  323,  322,
      321,   78,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   61,   61,   61,   61,   61,   61,   61,   61,  320,
       61,   77,   77,  319,  318,   77,   77,   87,  317,  316,

       87,   87,   87,   87,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,   72,  315,   72,   72,  148,  148,
      314,  313,  148,  148,  149,  149,  149,  149,  312,  311,
      310,  309,  308,  307,  306,  305,  304,  303,  302,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  285,  284,  281,  280,  279,
      278,  277,  274,  273,  272,  271,  270,  269,  268,  267,
      266,  265,  264,  263,  262,  261,  260,  259,  258,  257,
      256,  255,  254,  253,  252,  251,  250,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  236,  235,

      234,  233,  232,  231,  230,  225,  224,  223,  222,  221,
      220,  219,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  138,  201,  200,  199,  196,  195,  190,
      189,  188,  185,  184,  183,  182,  181,  180,  179,  176,
      175,  172,  171,  170,  169,  168,  167,  162,  161,  160,
      159,  158,  155,  152,  147,  143,  142,  141,  140,  138,
      137,  136,  125,  118,  117,  108,  100,   91,   84,   80,
       62,  341,    3,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,

      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341
    } ;

static const flex_int16_t yy_chk[540] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    5,    5,    6,
        6,    6,    8,    9,    9,   10,   14,   14,   15,   24,
       24,   19,   17,   16,   17,   17,   17,   17,   17,   17,
       17,   15,   15,   10,   10,   16,   16,   18,   19,  339,

       22,    8,   40,   19,   29,   29,   40,   18,   18,   35,
       32,   19,   22,   22,   29,   31,   32,   31,   33,   36,
       38,   35,   32,   35,   36,   36,   33,   39,   43,   36,
       53,   39,   38,   44,   33,   44,   54,   43,   55,   39,
       39,   46,   46,   44,   48,   48,   50,   50,   62,   44,
       51,   51,   51,   52,   52,   52,  338,   72,   72,   53,
       73,   73,   97,   77,  337,   54,   97,   55,   72,   82,
       82,   72,   76,   76,   76,   76,   76,   76,   76,   48,
       77,   86,   86,   90,   90,   77,   96,   96,  106,  110,
      118,  133,  106,   77,  122,  134,  123,  126,   55,  123,

      126,  122,  135,   62,  110,  148,  118,  144,  144,  164,
      164,  144,  144,  144,  144,  144,  144,  144,  165,  336,
      133,  205,  148,  197,  134,  165,  197,  148,  174,  333,
      174,  135,  174,  174,  205,  148,  202,  202,  202,  202,
      202,  202,  202,  203,  203,  203,  203,  203,  203,  203,
      238,  246,  238,  329,  246,  325,  324,  323,  203,  322,
      321,  319,  135,  312,  311,  310,  308,  307,  304,  303,
      302,  203,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  343,  343,  343,  343,  343,  343,  343,  343,  301,
      343,  344,  344,  300,  297,  344,  344,  345,  296,  295,

      345,  345,  345,  345,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  347,  293,  347,  347,  348,  348,
      292,  289,  348,  348,  349,  349,  349,  349,  288,  287,
      283,  282,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  269,  268,  267,  266,  264,  262,  261,  260,
      259,  258,  257,  255,  252,  250,  249,  244,  242,  241,
      240,  239,  236,  234,  233,  231,  230,  229,  228,  227,
      226,  225,  224,  222,  221,  220,  219,  218,  217,  216,
      215,  214,  212,  211,  209,  199,  198,  196,  195,  193,
      192,  191,  190,  189,  188,  187,  186,  185,  183,  182,

      181,  179,  178,  177,  176,  173,  172,  171,  169,  168,
      167,  166,  163,  162,  161,  160,  159,  158,  156,  153,
      150,  149,  145,  139,  131,  128,  127,  125,  124,  121,
      120,  119,  117,  116,  115,  114,  113,  112,  111,  109,
      108,  105,  103,  102,  101,  100,   99,   95,   94,   93,
       92,   91,   88,   83,   74,   71,   69,   66,   63,   61,
       59,   56,   45,   42,   41,   37,   34,   30,   23,   20,
       11,    3,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,

      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  341,  341
    } ;

static const flex_int16_t yy_rule_linenum[147] =
    {   0,
       44,   45,   47,   48,   49,   50,   51,   53,   54,   55,
       56,   57,   58,   59,   60,   61,   63,   64,   65,   66,
       67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
       78,   79,   80,   81,   82,   83,   84,   85,   86,   87,
       88,   89,   90,   91,   93,   94,   95,   96,   97,   98,
       99,  100,  102,  103,  104,  105,  106,  107,  108,  109,
      110,  111,  112,  113,  115,  116,  117,  118,  119,  120,
      121,  122,  123,  124,  125,  126,  128,  129,  130,  131,
      132,  133,  134,  135,  137,  138,  139,  140,  141,  142,
      143,  144,  145,  146,  147,  148,  150,  151,  152,  153,

      155,  156,  157,  159,  160,  161,  162,  163,  164,  165,
      166,  167,  168,  170,  172,  173,  174,  175,  176,  177,
      178,  179,  180,  181,  182,  183,  184,  185,  187,  188,
      189,  190,  192,  193,  194,  195,  196,  197,  199,  200,
      201,  202,  203,  204,  205,  207
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
#line 4 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
    #include <istream>

    #include "NikolaLexer.hpp"

    #ifdef YY_DECL
    #undef YY_DECL
    #endif

    using Parser = Nikola::SyntaxAnalysis::NikolaParser;
    using Lexer = Nikola::SyntaxAnalysis::NikolaLexer;

    #define YY_DECL Parser::symbol_type Lexer::lex()
    
    #define YY_USER_ACTION loc_.columns(yyleng);

    #ifdef YY_NULL
    #undef YY_NULL
    #endif
    #define YY_NULL Parser::make_YYEOF(loc_)
#line 750 "/home/aschiffe/Dev/Nikola-c/Nikolac/src/Parser/NikolaLexer.cpp"
#line 751 "/home/aschiffe/Dev/Nikola-c/Nikolac/src/Parser/NikolaLexer.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
#include <unistd.h>
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */
/* %if-bison-bridge */
/* %endif */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */
/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define ECHO LexerOutput( yytext, yyleng )
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
\
/* %if-c++-only C++ definition \ */\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
/* %endif */
/* %if-c++-only */
#define YY_FATAL_ERROR(msg) LexerError( msg )
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */
/* %ok-for-header */

/* %not-for-header */
/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define YY_DECL int yyFlexLexer::yylex()
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */
/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyin.rdbuf(std::cin.rdbuf());
/* %endif */

		if ( ! yyout )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyout.rdbuf(std::cout.rdbuf());
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
/* %% [7.0] user's declarations go here */
#line 39 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"


#line 42 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
    loc_.step();

#line 949 "/home/aschiffe/Dev/Nikola-c/Nikolac/src/Parser/NikolaLexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 342 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 473 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				std::cerr << "--scanner backing up\n";
			else if ( yy_act < 147 )
				std::cerr << "--accepting rule at line " << yy_rule_linenum[yy_act] <<
				         "(\"" << yytext << "\")\n";
			else if ( yy_act == 147 )
				std::cerr << "--accepting default rule (\"" << yytext << "\")\n";
			else if ( yy_act == 148 )
				std::cerr << "--(end of buffer or a NUL)\n";
			else
				std::cerr << "--EOF (start condition " << YY_START << ")\n";
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 44 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
loc_.lines(yyleng); loc_.step();
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 45 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
loc_.step();
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 47 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_INTEGER_LITERAL(yytext, loc_);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 48 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_REAL_LITERAL(yytext, loc_);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 49 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_COMPLEX_LITERAL(yytext, loc_);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 50 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_CHAR_LITERAL(yytext, loc_);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 51 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_STRING_LITERAL(yytext, loc_);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 53 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_LEFT_BRACKET(loc_);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 54 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_RIGHT_BRACKET(loc_);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 55 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_LEFT_PARENTHESIS(loc_);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 56 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_RIGHT_PARENTHESIS(loc_);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 57 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_LEFT_BRACE(loc_);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 58 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_RIGHT_BRACE(loc_);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 59 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_SEMI_COLON(loc_);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 60 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_COLON(loc_);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 61 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_RIGHT_ARROW(loc_);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 63 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_PLUS(loc_);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 64 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_MINUS(loc_);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 65 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_STAR(loc_);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 66 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_SLASH(loc_);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 67 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DOUBLE_SLASH(loc_);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 68 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_CARET(loc_);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 69 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_PERCENT(loc_);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 70 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_PLUS_ASSIGN(loc_);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 71 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_MINUS_ASSIGN(loc_);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 72 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_STAR_ASSIGN(loc_);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 73 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_SLASH_ASSIGN(loc_);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 74 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DOUBLE_SLASH_ASSIGN(loc_);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 75 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_CARET_ASSIGN(loc_);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 76 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_PERCENT_ASSIGN(loc_);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 78 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_PLUS(loc_);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 79 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_MINUS(loc_);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 80 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_STAR(loc_);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 81 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_SLASH(loc_);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 82 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_DOUBLE_SLASH(loc_);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 83 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_CARET(loc_);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 84 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_PERCENT(loc_);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 85 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_PLUS_ASSIGN(loc_);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 86 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_MINUS_ASSIGN(loc_);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 87 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_STAR_ASSIGN(loc_);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 88 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_SLASH_ASSIGN(loc_);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 89 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_DOUBLE_SLASH_ASSIGN(loc_);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 90 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_CARET_ASSIGN(loc_);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 91 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_PERCENT_ASSIGN(loc_);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 93 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DOUBLE_AMP(loc_);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 94 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DOUBLE_PIPE(loc_);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 95 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_BANG(loc_);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 96 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_LESS(loc_);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 97 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_LESS_EQ(loc_);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 98 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_SPACESHIP(loc_);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 99 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_GREATER(loc_);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 100 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_GREATER_EQ(loc_);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 102 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_AMP(loc_);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 103 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_PIPE(loc_);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 104 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DOUBLE_CARET(loc_);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 105 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_TILDE(loc_);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 106 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_LEFT_SHIFT(loc_);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 107 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_RIGHT_SHIFT(loc_);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 108 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_AMP_ASSIGN(loc_);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 109 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_PIPE_ASSIGN(loc_);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 110 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DOUBLE_CARET_ASSIGN(loc_);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 111 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_TILDE_ASSIGN(loc_);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 112 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_LEFT_SHIFT_ASSIGN(loc_);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 113 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_RIGHT_SHIFT_ASSIGN(loc_);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 115 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_AMP(loc_);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 116 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_PIPE(loc_);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 117 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_DOUBLE_CARET(loc_);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 118 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_TILDE(loc_);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 119 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_LEFT_SHIFT(loc_);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 120 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_RIGHT_SHIFT(loc_);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 121 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_AMP_ASSIGN(loc_);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 122 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_PIPE_ASSIGN(loc_);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 123 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_DOUBLE_CARET_ASSIGN(loc_);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 124 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_TILDE_ASSIGN(loc_);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 125 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_LEFT_SHIFT_ASSIGN(loc_);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 126 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VEC_RIGHT_SHIFT_ASSIGN(loc_);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 128 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_ASSIGN(loc_);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 129 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_LEFT_ARROW(loc_);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 130 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_PLUS_PLUS(loc_);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 131 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_MINUS_MINUS(loc_);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 132 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_ELLIPSIS(loc_);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 133 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_COLON_COLON(loc_);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 134 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DOT(loc_);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 135 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_QUESTION(loc_);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 137 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_INT8_T(loc_);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 138 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_INT16_T(loc_);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 139 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_INT32_T(loc_);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 140 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_INT64_T(loc_);}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 141 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_INT(loc_);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 142 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_REAL32_T(loc_);}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 143 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_REAL64_T(loc_);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 144 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_REAL(loc_);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 145 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_BOOL(loc_);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 146 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_CHAR(loc_);}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 147 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_MOD(loc_);}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 148 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_VOID(loc_);}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 150 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_TRUE(loc_);}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 151 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_FALSE(loc_);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 152 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_THIS(loc_);}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 153 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_NPTR(loc_);}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 155 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_LET(loc_);}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 156 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_CONST(loc_);}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 157 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_COMPEVAL(loc_);}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 159 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_PURE(loc_);}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 160 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_STATIC(loc_);}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 161 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_NOTHROW(loc_);}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 162 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_IN(loc_);}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 163 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_INOUT(loc_);}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 164 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_OUT(loc_);}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 165 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_MOVE(loc_);}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 166 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_OPERATOR(loc_);}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 167 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DELETE(loc_);}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 168 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DEFAULT(loc_);}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 170 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DEFINE(loc_);}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 172 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_IF(loc_);}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 173 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_ELSE(loc_);}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 174 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_ELSE_IF(loc_);}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 175 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_FOR(loc_);}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 176 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DO(loc_);}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 177 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_WHILE(loc_);}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 178 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_TRY(loc_);}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 179 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_CATCH(loc_);}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 180 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_THROW(loc_);}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 181 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_BREAK(loc_);}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 182 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_RETURN(loc_);}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 183 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_CONTINUE(loc_);}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 184 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_MATCH(loc_);}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 185 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_WHEN(loc_);}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 187 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_TYPESET(loc_);}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 188 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_TEMPLATE(loc_);}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 189 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_WHERE(loc_);}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 190 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_TYPE(loc_);}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 192 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_MODULE(loc_);}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 193 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_NAMESPACE(loc_);}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 194 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_IMPORT(loc_);}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 195 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_FROM(loc_);}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 196 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_AS(loc_);}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 197 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_WITH(loc_);}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 199 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_IS(loc_);}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 200 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_SIZEOF(loc_);}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 201 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_TYPEOF(loc_);}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 202 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_STATIC_ASSERT(loc_);}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 203 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_ASSERT(loc_);}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 204 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_NEW(loc_);}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 205 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_DYNAMIC(loc_);}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 207 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_IDENTIFIER(yytext, loc_);}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 209 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
{return Parser::make_YYEOF(loc_);}
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 211 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1769 "/home/aschiffe/Dev/Nikola-c/Nikolac/src/Parser/NikolaLexer.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
/* %endif */
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */
/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
int yyFlexLexer::yy_get_next_buffer()
/* %endif */
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */
/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_get_previous_state()
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 342 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
/* %endif */
{
	int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 342 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 341);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyunput( int c, char* yy_bp)
/* %endif */
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */
/* %endif */
#endif

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yyinput()
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyrestart( std::istream& input_file )
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/* %if-c++-only */
/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_load_buffer_state()
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
/* %endif */
/* %if-c++-only */
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
/* %endif */
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/* %if-c++-only */
/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

/* %if-c-only */
/* %endif */
/* %if-c++-only */
	b->yy_input_file = file.rdbuf();
/* %endif */
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */
/* %endif */
/* %if-c++-only */
	b->yy_is_interactive = 0;
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypop_buffer_state (void)
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yyensure_buffer_stack(void)
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_push_state( int _new_state )
/* %endif */
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_pop_state()
/* %endif */
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yy_top_state()
/* %endif */
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* %if-reentrant */
/* %endif */
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 211 "/home/aschiffe/Dev/Nikola-c/Nikolac/include/Parser/NikolaLexer.ll"

namespace Nikola::SyntaxAnalysis
{
    NikolaLexer::NikolaLexer(std::istream& in)
    : yyFlexLexer{&in}, loc_{}
    {

    }
}
